[versions]
kotlin = "2.2.10"
detekt = "1.23.8"
dokka = "2.0.0"
gitVersion = "4.0.0"
gradle-versions = "0.53.0"
jreleaser = "1.20.0"
jsoup = "1.18.3"
kotest = "6.0.3"
kotlinLogging = "3.0.5"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.9.0"
kover = "0.9.2"
ktor = "3.3.0"
logback = "1.5.19"
sonarqube = "6.3.1.5724"

[plugins]
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
git-version = { id = "com.palantir.git-version", version.ref = "gitVersion" }

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinLogging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-data-conversion = { module = "io.ktor:ktor-server-data-conversion" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
ktor-client-extras = [
    "ktor-client-encoding",
    "ktor-client-content-negotiation",
]
ktor-server = [
    "ktor-server-cio",
    "ktor-server-content-negotiation",
    "ktor-server-data-conversion",
    "ktor-server-status-pages",
    "ktor-server-resources",
]
kotest = [
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-property",
]
