name: Publish snapshot to Sonatype Nexus
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v2
      - name: â˜•ï¸ Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: âš™ï¸ Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: ğŸš€ Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -x test publishToSonatype closeAndReleaseStagingRepository
        env:
          SONATYPE_USER: ${{secrets.SONATYPE_USER}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}